# Job positions and their associated skills

job_positions = [
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "DevOps Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "AI Engineer",
    "Cloud Architect",
    "System Administrator",
    "Database Administrator",
    "Product Manager",
    "Project Manager",
    "UI/UX Designer",
    "Quality Assurance Engineer",
    "Security Engineer",
    "Mobile Developer",
    "Business Analyst",
    "Data Engineer",
    "Network Engineer",
    "Blockchain Developer",
    "AR/VR Developer",
    "IoT Engineer",
    "Site Reliability Engineer",
    "Technical Architect",
    "Embedded Systems Engineer",
    "Game Developer",
    "Information Security Analyst",
    "Cloud Security Engineer",
    "Data Privacy Officer"
]

skills_by_position = {
    "Software Engineer": ["Python", "Java", "C++", "Data Structures", "Algorithms", "Git", "SQL", "Problem Solving", "System Design"],
    "Frontend Developer": ["HTML", "CSS", "JavaScript", "React", "Vue.js", "Angular", "Responsive Design", "Web Performance", "TypeScript", "Web Accessibility"],
    "Backend Developer": ["Python", "Java", "Node.js", "Databases", "APIs", "Server Management", "Security", "Microservices", "Message Queues"],
    "Full Stack Developer": ["Frontend Technologies", "Backend Technologies", "Databases", "Version Control", "DevOps", "API Design", "System Architecture"],
    "DevOps Engineer": ["CI/CD", "Docker", "Kubernetes", "AWS/Azure/GCP", "Infrastructure as Code", "Shell Scripting", "Monitoring Tools", "Configuration Management"],
    "Data Scientist": ["Python", "R", "SQL", "Machine Learning", "Statistics", "Data Visualization", "Big Data", "Feature Engineering", "A/B Testing"],
    "Machine Learning Engineer": ["Python", "TensorFlow", "PyTorch", "Deep Learning", "NLP", "Computer Vision", "MLOps", "Model Deployment"],
    "AI Engineer": ["Machine Learning", "Deep Learning", "NLP", "Python", "AI Frameworks", "Mathematics", "Neural Networks", "Reinforcement Learning"],
    "Cloud Architect": ["AWS/Azure/GCP", "Cloud Security", "Networking", "Scalability", "Cost Optimization", "Multi-cloud Strategy", "Cloud Migration"],
    "System Administrator": ["Linux", "Windows Server", "Networking", "Security", "Backup & Recovery", "Automation", "Monitoring"],
    "Database Administrator": ["SQL", "Database Design", "Performance Tuning", "Backup & Recovery", "Security", "NoSQL", "Data Migration"],
    "Product Manager": ["Product Strategy", "User Research", "Agile", "Roadmapping", "Stakeholder Management", "Market Analysis", "Product Analytics"],
    "Project Manager": ["Project Planning", "Agile/Scrum", "Risk Management", "Stakeholder Management", "Budgeting", "Team Leadership"],
    "UI/UX Designer": ["User Research", "Wireframing", "Prototyping", "Visual Design", "Usability Testing", "Design Systems", "Interaction Design"],
    "Quality Assurance Engineer": ["Test Planning", "Automation Testing", "Manual Testing", "Bug Tracking", "Performance Testing", "Security Testing", "API Testing"],
    "Security Engineer": ["Network Security", "Penetration Testing", "Security Tools", "Risk Assessment", "Compliance", "Incident Response", "Security Architecture"],
    "Mobile Developer": ["iOS/Android", "React Native", "Flutter", "Mobile UI/UX", "App Performance", "Mobile Security", "App Store Optimization"],
    "Business Analyst": ["Requirements Gathering", "Data Analysis", "Process Modeling", "Documentation", "Communication", "Business Process Optimization"],
    "Data Engineer": ["ETL", "Data Warehousing", "Big Data", "SQL", "Python", "Data Modeling", "Stream Processing", "Data Pipeline Design"],
    "Network Engineer": ["Network Protocols", "Router/Switch Configuration", "Network Security", "Troubleshooting", "Network Monitoring", "SDN"],
    "Blockchain Developer": ["Smart Contracts", "Solidity", "Web3.js", "Ethereum", "Cryptography", "DApp Development", "Blockchain Protocols"],
    "AR/VR Developer": ["Unity", "Unreal Engine", "3D Modeling", "Computer Vision", "Spatial Computing", "AR/VR SDKs", "User Experience Design"],
    "IoT Engineer": ["Embedded Systems", "Sensor Programming", "IoT Protocols", "Edge Computing", "MQTT", "Hardware Integration", "IoT Security"],
    "Site Reliability Engineer": ["Infrastructure Automation", "Monitoring", "Incident Response", "Performance Optimization", "Chaos Engineering", "Load Balancing"],
    "Technical Architect": ["System Design", "Architecture Patterns", "Technology Strategy", "Scalability Planning", "Integration Architecture", "Technical Leadership"],
    "Embedded Systems Engineer": ["C/C++", "Microcontrollers", "RTOS", "Hardware Interfaces", "Firmware Development", "Device Drivers", "Digital Signal Processing"],
    "Game Developer": ["Game Engines", "3D Graphics", "Physics Programming", "Animation", "Game AI", "Multiplayer Networking", "Game Design Principles"],
    "Information Security Analyst": ["Threat Analysis", "Security Monitoring", "Incident Response", "Vulnerability Assessment", "Security Policies", "SIEM Tools"],
    "Cloud Security Engineer": ["Cloud Security Architecture", "Identity Management", "Security Automation", "Compliance Frameworks", "Cloud Native Security", "DevSecOps"],
    "Data Privacy Officer": ["GDPR", "Data Protection Laws", "Privacy Impact Assessment", "Data Governance", "Privacy by Design", "Compliance Management"]
}