[build]
base = "/"
publish = "public"
command = """
  apt-get update && \
  apt-get install -y python3-dev portaudio19-dev && \
  python -m pip install --upgrade pip && \
  pip install wheel setuptools python-distutils-extra && \
  pip install -r requirements.txt && \
  mkdir -p public && \
  python -m streamlit run main.py --server.port $PORT
"""
functions = "netlify/functions"

[build.environment]
PYTHON_VERSION = "3.11"
GROQ_API_KEY = "${GROQ_API_KEY}"
NODE_VERSION = "16"

[[redirects]]
from = "/*"
to = "/"
status = 200
force = true

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

[dev]
command = "streamlit run main.py"
targetPort = 8501
port = 8888
publish = "public"
autoLaunch = false

[build.processing]
skip_processing = true

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true